### ISSUE TITLE
Handle deleted files from files ystem in a better way

### ISSUE THREAD

**Issue by CarolusMagnus** [equeim/unplayer#40] opened 2018-07-22 17:17 UTC
Deleting a file from file system (outside Unplayer), which is currently in the library, confuses Unplayer: selecting a track from the same album leads to the wrong  track played. Also the "update library" doesn't help, just a full reset of the library works. 

Even worse, if the last played file is deleted , when Unplayer is not running, it crashes at startup. Then it only helps to delete the config file.

**Comment by equeim** [comment] 2018-08-19 15:10
>Also the "update library" doesn't help, just a full reset of the library works.

That's strange, I can't reproduce this issue. When library is updated, unplayer loads all files from database and checks if they are exist, actually files (not directories) and are readable. If not, they are removed from database. If you run unplayer in terminal, does it print anything when you update library and deleted file is not removed from db? Where is deleted file located? Could send me database file (~/.local/share/harbour-unplayer/harbour-unplayer/library.sqlite) prior to deletion (if it doesn't contain your private information)?

**Comment by equeim** [comment] 2019-05-02 22:53
Should be fixed by now.

**Closed as completed by equeim** 2019-05-02 22:53 UTC
